// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var GoL = 0;

var Index = 0;

var Component1 = 0;

var Component2 = 0;

var Scratchpad = 0;

exports.GoL = GoL;
exports.Index = Index;
exports.Component1 = Component1;
exports.Component2 = Component2;
exports.Scratchpad = Scratchpad;
/* No side effect */
