// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var foo = /* array */[
  1,
  2,
  3
];

Pervasives.print_int($$Array.fold_left((function (acc, item) {
            return acc + item | 0;
          }), 0, foo));

exports.foo = foo;
/*  Not a pure module */
